name: smart-energy
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy=1.25.0
  - pandas=2.1.1
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - pyserial=3.5
  - pytest=7.4.0
  - scikit-learn=1.3.2
  - pip
  - pip:
      - textblob==0.17.1
