name: Smart Energy Monitoring CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Miniconda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          environment-file: environment.yml
          activate-environment: smart-energy

      # Step 3: Create folders
      - name: Create required folders
        run: |
          mkdir -p rs485_logs
          mkdir -p plots
          mkdir -p data

      # Step 4: Run mock RS-485 logger test
      - name: Run mock logger test
        run: |
          pytest tests/test_mock_logger.py

      # Step 5: Replay synthetic CSV
      - name: Replay synthetic CSV
        run: python src/replay_logger.py

      # Step 6: Generate PNG chart from CSV
      - name: Generate load chart
        run: python plots/generate_plot.py

      # Step 7: Upload artifacts (CSV + PNG)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-artifacts
          path: |
            rs485_logs/
            plots/
            data/sample.csv
