name: Smart Energy Monitoring CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: smart-energy
          use-mamba: true
          force: true

      - name: Create required folders
        run: mkdir -p rs485_logs plots data

      - name: Run mock logger test
        run: conda run -n smart-energy pytest tests/test_mock_logger.py

      - name: Replay synthetic CSV
        run: conda run -n smart-energy python src/replay_logger.py

      - name: Generate load chart
        run: conda run -n smart-energy python plots/generate_plot.py

      - name: Upload metrics/artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-artifacts
          path: |
            rs485_logs/
            plots/
            data/sample.csv
