name: RS485 Script CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyserial

      - name: Create log folder
        run: mkdir -p rs485_logs

      - name: Run RS485 script (mocked)
        run: python mock_rs485.py
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ml-house-prices
          environment-file: environment.yml
          python-version: 3.11
