name: Smart Energy Monitoring CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Miniconda and create env from environment.yml
    
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
            auto-update-conda: true
            environment-file: environment.yml
            activate-environment: smart-energy
            use-mamba: true


      # Step 3: Verify conda environment
      - name: Verify environment
        run: conda info && conda list

      # Step 4: Create required folders
      - name: Create folders
        run: |
          mkdir -p rs485_logs plots data

      # Step 5: Run mock RS-485 logger test
      - name: Run mock logger test
        run: pytest tests/test_mock_logger.py

      # Step 6: Replay synthetic CSV
      - name: Replay synthetic CSV
        run: python src/replay_logger.py

      # Step 7: Generate PNG chart
      - name: Generate load chart
        run: python plots/generate_plot.py

      # Step 8: Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-artifacts
          path: |
            rs485_logs/
            plots/
            data/sample.csv
